baseURL = "https://samesense.github.io/blog/"
languageCode = "en-us"
title = "blog"

name = "Hyde"
license = "MIT"
tags = ["blog", "genomics"]
features = ["blog", "themes", "disqus"]

[author]
    name = "samesense"
    homepage = "https://samesense.github.io/blog/"

[params]
    description = 'A computational biology focused blog maintained by <a href="http://twitter.com/oncolytic">@oncolytic</a>.'